import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import RemainingSecounds from '@/components/Timer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="flex w-full justify-center bg-gray-900 items-center p-3">
                    <RemainingSecounds />
                </div>
                {children}
            </body>
        </html>
    )
}
